app:
  name: The MovieVerse
  description: "Explore The MovieVerse to discover and learn about your favorite movies, directors, actors, and more."
  language: en
  theme_color: "#7378c5"
  author: Son Nguyen Hoang

meta:
  viewport: "width=device-width, initial-scale=1.0"
  robots: "index, follow"
  rating: "General"
  revisit_after: "3 days"
  distribution: "global"
  keywords: "movies, film guide, directors, actors, movie genres, cinema, film reviews"

og:
  title: "The MovieVerse - Your Ultimate Movie Guide"
  type: website
  url: "https://movie-verse.com/"
  image: "https://movie-verse.com/images/image.png"
  description: "Explore The MovieVerse to discover and learn about your favorite movies, directors, actors, and more."
  locale: en_US
  site_name: The MovieVerse

twitter:
  card: "https://movie-verse.com/images/image.png"
  title: "The MovieVerse - Your Ultimate Movie Guide"
  description: "Explore The MovieVerse to discover and learn about your favorite movies, directors, actors, and more."
  image: "https://movie-verse.com/images/image.png"

analytics:
  google_tag_manager_id: G-CQKJ67FXZ4

resources:
  css:
    - "src/css/style.css"
    - "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
  js:
    - "src/js/settings.js"
    - "index.js"
    - "https://www.googletagmanager.com/gtag/js?id=G-CQKJ67FXZ4"
  favicon: "images/favicon.ico"
  manifest: "manifest.json"
  service_worker: "src/js/service-worker.js"

paths:
  about: "./src/html/about.html"
  favorites: "./src/html/favorites.html"
  user_profile: "./src/html/user-profile.html"
  settings: "src/html/settings.html"
  movie_match: "src/html/movie-match.html"
  movie_timeline: "src/html/movie-timeline.html"
  chatbot: "src/html/chatbot.html"
  trivia: "./src/html/trivia.html"
