apiVersion: v1
kind: ServiceAccount
metadata:
  name: movieverse-sa
  namespace: movieverse
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/movieverse-eks-pod-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: movieverse-role
  namespace: movieverse
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: movieverse-rolebinding
  namespace: movieverse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: movieverse-role
subjects:
- kind: ServiceAccount
  name: movieverse-sa
  namespace: movieverse
