apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: movieverse-ai-secrets
  namespace: movieverse
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: movieverse-secret-store
    kind: ClusterSecretStore
  target:
    name: movieverse-ai-secrets
    creationPolicy: Owner
  data:
    - secretKey: MOVIEVERSE_AI_POSTGRES_DSN
      remoteRef:
        key: movieverse/ai
        property: postgres_dsn
    - secretKey: MOVIEVERSE_AI_MYSQL_DSN
      remoteRef:
        key: movieverse/ai
        property: mysql_dsn
    - secretKey: MOVIEVERSE_AI_MONGO_URI
      remoteRef:
        key: movieverse/ai
        property: mongo_uri
    - secretKey: MOVIEVERSE_AI_REDIS_URL
      remoteRef:
        key: movieverse/ai
        property: redis_url
    - secretKey: MOVIEVERSE_AI_KAFKA_BOOTSTRAP_SERVERS
      remoteRef:
        key: movieverse/ai
        property: kafka_bootstrap_servers
    - secretKey: MOVIEVERSE_AI_S3_ACCESS_KEY
      remoteRef:
        key: movieverse/ai
        property: s3_access_key
    - secretKey: MOVIEVERSE_AI_S3_SECRET_KEY
      remoteRef:
        key: movieverse/ai
        property: s3_secret_key
