apiVersion: v1
kind: Service
metadata:
  name: movieverse-ai-api
  namespace: movieverse
spec:
  selector:
    app: movieverse-ai-api
  ports:
    - name: http
      port: 9000
      targetPort: 9000
  type: ClusterIP
